Metadata:
  ServiceCatalog:
    ProductVersion:
      Description: Add 'ReadPrincipalArns', 'WritePrincipalArns', 'BucketVersioningStatus' parameters

Parameters:
  BucketName:
    Type: String
    Default: ""
    Description: >-
      Optional. If a bucket name is not provided, a random name will be generated.
  ReadPrincipalArns:
    Type: CommaDelimitedList
    Default: ""
    AllowedPattern: '(^$|^arn:aws(-us-gov)?:iam::\d{12}:[\w-]+\/.+$)'
    Description: >-
      Optional. Grant AWS principals read access to the bucket. Example: arn:aws:iam::111111111111:role/RoleOne,arn:aws:iam::111111111111:role/RoleTwo
  WritePrincipalArns:
    Type: CommaDelimitedList
    Default: ""
    AllowedPattern: '(^$|^arn:aws(-us-gov)?:iam::\d{12}:[\w-]+\/.+$)'
    Description: >-
      Optional. Grant AWS principals write access to the bucket. Example: arn:aws:iam::111111111111:role/RoleOne,arn:aws:iam::111111111111:role/RoleTwo
  BucketVersioningStatus:
    Type: String
    AllowedValues: [Enabled, Suspended]
    Default: Suspended

Conditions:
  BucketNameProvided:
    Fn::Not:
      - Fn::Equals:
        - Ref: BucketName
        - ""
  ReadPrincipalArnsProvided:
    Fn::Not:
      - Fn::Equals:
        - Fn::Join:
          - ""
          - Ref: ReadPrincipalArns
        - ""
  WritePrincipalArnsProvided:
    Fn::Not:
      - Fn::Equals:
        - Fn::Join:
          - ""
          - Ref: WritePrincipalArns
        - ""
  ReadOrWritePrincipalArnsProvided:
    Fn::Or:
      - Condition: ReadPrincipalArnsProvided
      - Condition: WritePrincipalArnsProvided

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName:
        Fn::If:
          - BucketNameProvided
          - Ref: BucketName
          - Ref: AWS::NoValue
      VersioningConfiguration:
        Status:
          Ref: BucketVersioningStatus
      Tags:
        - Key: MyTagKeyInCfnTempl
          Value: MyTagValueInCfnTempl

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: ReadOrWritePrincipalArnsProvided
    Properties:
      Bucket:
        Ref: Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Fn::If:
            - ReadPrincipalArnsProvided
            - Action:
                - 's3:Get*'
                - 's3:List*'
              Effect: Allow
              Resource:
                - Fn::Sub: '${Bucket.Arn}'
                - Fn::Sub: '${Bucket.Arn}/*'
              Principal:
                AWS:
                  Ref: ReadPrincipalArns
            - Ref: AWS::NoValue
          - Fn::If:
            - WritePrincipalArnsProvided
            - Action:
                - 's3:PutObject'
                - 's3:PutObjectTagging'
                - 's3:DeleteObject'
              Effect: Allow
              Resource:
                - Fn::Sub: '${Bucket.Arn}'
                - Fn::Sub: '${Bucket.Arn}/*'
              Principal:
                AWS:
                  Ref: WritePrincipalArns
            - Ref: AWS::NoValue
